version: '3.8'
services:
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile-frontend
    ports:
      - "5173:80"
    networks:
      - physiobit-net

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile-backend
    ports:
     - "7970:7970"
    networks:
      - physiobit-net

networks:
  physiobit-net:
    driver: bridge