version: '3.8'
services:
  frontend:
    container_name: physiobit-frontend
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "${WEB_PORT}:80"
    networks:
      - physiobit-net

  backend:
    container_name: physiobit-backend
    build:
      context: ./backend
      dockerfile: Dockerfile    
    ports:
      - "${API_PORT}:7970"
    environment:
      NODE_ENV: ${NODE_ENV},
      API_PORT: ${API_PORT},
      MONGODB_URI: ${MONGODB_URI} 
      FITBIT_CLIENT_ID: ${FITBIT_CLIENT_ID}
      FITBIT_CLIENT_SECRET: ${FITBIT_CLIENT_SECRET}
      BASE_URL: ${BASE_URL}
      REDIRECT_URI: ${REDIRECT_URI}
      SESSION_SECRET: ${SESSION_SECRET}
      SENDGRID_API_KEY: ${SENDGRID_API_KEY}
      SENDGRID_FROM: ${SENDGRID_FROM}
      ADMIN_EMAIL: ${ADMIN_EMAIL}
    networks:
      - physiobit-net
    healthcheck:
    test: ["CMD", "curl", "-f", "http://localhost:7970/health"]
    interval: 30s
    timeout: 10s
    retries: 3
    start_period: 10s

  mongo:
    container_name: physiobit-mongo
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: physiobit
      MONGO_INITDB_ROOT_PASSWORD: physiobit
      MONGO_INITDB_DATABASE: physiobit
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - physiobit-net
    healthcheck:
      test: echo 'db.runCommand("ping")' | mongo physiobit --quiet
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  physiobit-net:
    driver: bridge

volumes:
  mongodb_data:
